name: Go

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      # build for amd64/arm64 on ubuntu, mac, and windows
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go_arch: [amd64, arm64]
        include:
          - os: ubuntu-latest
            go_os: "linux"
          - os: macos-latest
            go_os: "darwin"
          - os: windows-latest
            go_os: "windows"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build
        env:
          GOOS: ${{ matrix.go_os }}
          GOARCH: ${{ matrix.go_arch }}
        run: |
          go build -o build/choirpack-${{ matrix.go_os }}-${{ matrix.go_arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: choirpack-${{ matrix.go_os }}-${{ matrix.go_arch }}
          path: build/choirpack-${{ matrix.go_os }}-${{ matrix.go_arch }}
